# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_commandline_faultyproduct_history_productcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandline',
            name='id_product',
        ),
        migrations.AddField(
            model_name='commandline',
            name='id_products',
            field=models.ManyToManyField(to='shop.Product'),
        ),
        migrations.RemoveField(
            model_name='history',
            name='id_product',
        ),
        migrations.AddField(
            model_name='history',
            name='id_product',
            field=models.ManyToManyField(to='shop.Product'),
        ),
    ]
